=== cthing/gradle-locc/src/main/resources/locc-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:lc="http://www.cthing.com/locc"
        targetNamespace="http://www.cthing.com/locc">

    <annotation>
        <documentation>
            Schema describing the XML report generated by the gradle-locc Gradle plugin.
        </documentation>
    </annotation>

    <element name="locc" type="lc:loccSchema">
        <annotation>
            <documentation>
                Top level element. Attributes on this element provide information about the version of the file
                format, the date on which the report was produced and the project containing the counted files.
            </documentation>
        </annotation>
    </element>
    <element name="languages" type="lc:languagesSchema">
        <annotation>
            <documentation>
                Container for the list of all languages found in the counted files. Attributes on this element
                provide the total count of languages and lines in all counted files.
            </documentation>
        </annotation>
    </element>
    <element name="language" type="lc:languageSchema">
        <annotation>
            <documentation>
                Information about a language found in the counted files. Attributes of this element provide
                the language and the lines counted for that language.
            </documentation>
        </annotation>
    </element>
    <element name="files" type="lc:filesSchema">
        <annotation>
            <documentation>
                Container for the list of all files counted. Attributes on this element provide the total count
                of files and lines counted.
            </documentation>
        </annotation>
    </element>
    <element name="file" type="lc:fileSchema">
        <annotation>
            <documentation>
                Information about a counted file.
            </documentation>
        </annotation>
    </element>

    <complexType name="loccSchema">
        <choice>
            <element ref="lc:languages"/>
            <element ref="lc:files"/>
        </choice>
        <attribute name="formatVersion" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    The version of this schema.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="date" type="dateTime" use="required">
            <annotation>
                <documentation>
                    Date and time in ISO 8601 format when the report was generated.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="projectName" type="string" use="required">
            <annotation>
                <documentation>
                    Name of the root Gradle project that generated the report.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="projectVersion" type="string" use="required">
            <annotation>
                <documentation>
                    Version of the Gradle project that generated the report.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="filesSchema">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <element ref="lc:file"/>
        </sequence>
        <attribute name="numFiles" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Total number of files counted and unrecognized.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="numUnrecognized" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Number of files that were not counted because they were not recognized.
                </documentation>
            </annotation>
        </attribute>
        <attributeGroup ref="lc:countAttrs"/>
    </complexType>

    <complexType name="fileSchema">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <element ref="lc:language"/>
        </sequence>
        <attribute name="pathname" type="string" use="required">
            <annotation>
                <documentation>
                    Pathname of the file relative to the root of the Gradle project.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="languagesSchema">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <element ref="lc:language"/>
        </sequence>
        <attribute name="numLanguages" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Total number of languages detected in the counted files.
                </documentation>
            </annotation>
        </attribute>
        <attributeGroup ref="lc:countAttrs"/>
    </complexType>

    <complexType name="languageSchema">
        <attribute name="name" type="token" use="required">
            <annotation>
                <documentation>
                    Identifier for the language.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="displayName" type="string" use="required">
            <annotation>
                <documentation>
                    Name of the language for display in a user interface.
                </documentation>
            </annotation>
        </attribute>
        <attributeGroup ref="lc:countAttrs"/>
    </complexType>

    <attributeGroup name="countAttrs">
        <attribute name="totalLines" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Total number of lines of counted. Depending on the context in which this
                    attribute is presented, it can mean the total number of lines in a file or
                    in a specific language.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="codeLines" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Number of lines of code counted. Depending on the context in which this
                    attribute is presented, it can mean the number of code lines in a file or
                    in a specific language.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="commentLines" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Number of comment lines counted. Depending on the context in which this
                    attribute is presented, it can mean the number of comment lines in a file or
                    in a specific language. Note that lines containing both code and comments are
                    counted as code lines.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="blankLines" type="nonNegativeInteger" use="required">
            <annotation>
                <documentation>
                    Number of blank lines counted. Depending on the context in which this
                    attribute is presented, it can mean the number of blank lines in a file or
                    in a specific language.
                </documentation>
            </annotation>
        </attribute>
    </attributeGroup>
</schema>

=== cthing/gradle-locc/src/test/resources/reports/complex-project/locc.xml
<?xml version="1.0" standalone="yes"?>
<locc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.cthing.com/schemas/locc-1.xsd locc-1.xsd" formatVersion="1" date="${xmlunit.ignore}" projectName="complex-project" projectVersion="unspecified" xmlns="http://www.cthing.com/locc">
    <languages numLanguages="5" totalLines="148" codeLines="82" commentLines="44" blankLines="22">
        <language name="CHeader" displayName="C Header" totalLines="13" codeLines="10" commentLines="0" blankLines="3"/>
        <language name="Cpp" displayName="C++" totalLines="21" codeLines="18" commentLines="0" blankLines="3"/>
        <language name="Java" displayName="Java" totalLines="76" codeLines="22" commentLines="44" blankLines="10"/>
        <language name="Kotlin" displayName="Kotlin" totalLines="18" codeLines="15" commentLines="0" blankLines="3"/>
        <language name="Swift" displayName="Swift" totalLines="20" codeLines="17" commentLines="0" blankLines="3"/>
    </languages>
    <files numFiles="12" numUnrecognized="0" totalLines="148" codeLines="82" commentLines="44" blankLines="22">
        <file pathname="project1/src/main/java/com/cthing/project1/HelloWorld.java">
            <language name="Java" displayName="Java" totalLines="29" codeLines="10" commentLines="15" blankLines="4"/>
        </file>
        <file pathname="project1/src/main/java/com/cthing/project1/package-info.java">
            <language name="Java" displayName="Java" totalLines="9" codeLines="1" commentLines="7" blankLines="1"/>
        </file>
        <file pathname="project2/src/main/java/com/cthing/project2/GoodbyeWorld.java">
            <language name="Java" displayName="Java" totalLines="29" codeLines="10" commentLines="15" blankLines="4"/>
        </file>
        <file pathname="project2/src/main/java/com/cthing/project2/package-info.java">
            <language name="Java" displayName="Java" totalLines="9" codeLines="1" commentLines="7" blankLines="1"/>
        </file>
        <file pathname="project3/src/main/cpp/app.cpp">
            <language name="Cpp" displayName="C++" totalLines="13" codeLines="11" commentLines="0" blankLines="2"/>
        </file>
        <file pathname="project3/src/main/headers/app.h">
            <language name="CHeader" displayName="C Header" totalLines="13" codeLines="10" commentLines="0" blankLines="3"/>
        </file>
        <file pathname="project3/src/test/cpp/app_test.cpp">
            <language name="Cpp" displayName="C++" totalLines="8" codeLines="7" commentLines="0" blankLines="1"/>
        </file>
        <file pathname="project4/src/main/swift/Hello.swift">
            <language name="Swift" displayName="Swift" totalLines="5" codeLines="5" commentLines="0" blankLines="0"/>
        </file>
        <file pathname="project4/src/test/swift/HelloTests.swift">
            <language name="Swift" displayName="Swift" totalLines="12" codeLines="10" commentLines="0" blankLines="2"/>
        </file>
        <file pathname="project4/src/test/swift/LinuxMain.swift">
            <language name="Swift" displayName="Swift" totalLines="3" codeLines="2" commentLines="0" blankLines="1"/>
        </file>
        <file pathname="project5/src/main/kotlin/org/example/Library.kt">
            <language name="Kotlin" displayName="Kotlin" totalLines="7" codeLines="6" commentLines="0" blankLines="1"/>
        </file>
        <file pathname="project5/src/test/kotlin/org/example/LibraryTest.kt">
            <language name="Kotlin" displayName="Kotlin" totalLines="11" codeLines="9" commentLines="0" blankLines="2"/>
        </file>
    </files>
</locc>

=== cthing/gradle-locc/src/test/resources/reports/augmented-project/locc.xml
<?xml version="1.0" standalone="yes"?>
<locc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.cthing.com/schemas/locc-1.xsd locc-1.xsd" formatVersion="1" date="${xmlunit.ignore}" projectName="augmented-project" projectVersion="unspecified" xmlns="http://www.cthing.com/locc">
    <languages numLanguages="5" totalLines="530" codeLines="251" commentLines="165" blankLines="114">
        <language name="Css" displayName="CSS" description="Cascading Style Sheets language" website="https://www.w3.org/Style/CSS/" totalLines="7" codeLines="7" commentLines="0" blankLines="0"/>
        <language name="GradleGroovy" displayName="GradleGroovy" description="Gradle Groovy build file" website="https://gradle.org/" totalLines="11" codeLines="10" commentLines="0" blankLines="1"/>
        <language name="Html" displayName="HTML" description="HyperText Markup Language" website="https://en.wikipedia.org/wiki/HTML" totalLines="12" codeLines="12" commentLines="0" blankLines="0"/>
        <language name="Java" displayName="Java" description="Java programming language" website="https://en.wikipedia.org/wiki/Java_(programming_language)" totalLines="59" codeLines="21" commentLines="29" blankLines="9"/>
        <language name="Xml" displayName="XML" description="Extensible Markup Language" website="https://www.w3.org/XML/" totalLines="441" codeLines="201" commentLines="136" blankLines="104"/>
    </languages>
    <files numFiles="7" numUnrecognized="0" totalLines="530" codeLines="251" commentLines="165" blankLines="114">
        <file pathname="build.gradle" numLanguages="1" totalLines="11" codeLines="10" commentLines="0" blankLines="1">
            <language name="GradleGroovy" totalLines="11" codeLines="10" commentLines="0" blankLines="1"/>
        </file>
        <file pathname="dev/checkstyle.xml" numLanguages="1" totalLines="441" codeLines="201" commentLines="136" blankLines="104">
            <language name="Xml" totalLines="441" codeLines="201" commentLines="136" blankLines="104"/>
        </file>
        <file pathname="src/main/java/com/cthing/testproject/HelloWorld.java" numLanguages="1" totalLines="32" codeLines="11" commentLines="17" blankLines="4">
            <language name="Java" totalLines="32" codeLines="11" commentLines="17" blankLines="4"/>
        </file>
        <file pathname="src/main/java/com/cthing/testproject/package-info.java" numLanguages="1" totalLines="10" codeLines="1" commentLines="8" blankLines="1">
            <language name="Java" totalLines="10" codeLines="1" commentLines="8" blankLines="1"/>
        </file>
        <file pathname="src/main/resources/sample.css" numLanguages="1" totalLines="7" codeLines="7" commentLines="0" blankLines="0">
            <language name="Css" totalLines="7" codeLines="7" commentLines="0" blankLines="0"/>
        </file>
        <file pathname="src/main/resources/sample.html" numLanguages="1" totalLines="12" codeLines="12" commentLines="0" blankLines="0">
            <language name="Html" totalLines="12" codeLines="12" commentLines="0" blankLines="0"/>
        </file>
        <file pathname="src/test/java/com/cthing/testproject/HelloWorldTest.java" numLanguages="1" totalLines="17" codeLines="9" commentLines="4" blankLines="4">
            <language name="Java" totalLines="17" codeLines="9" commentLines="4" blankLines="4"/>
        </file>
    </files>
</locc>

=== cthing/gradle-locc/src/test/resources/reports/simple-project/locc.xml
<?xml version="1.0" standalone="yes"?>
<locc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.cthing.com/schemas/locc-1.xsd locc-1.xsd" formatVersion="1" date="${xmlunit.ignore}" projectName="simple-project" projectVersion="unspecified" xmlns="http://www.cthing.com/locc">
    <languages numLanguages="3" totalLines="78" codeLines="40" commentLines="29" blankLines="9">
        <language name="Css" displayName="CSS" totalLines="7" codeLines="7" commentLines="0" blankLines="0"/>
        <language name="Html" displayName="HTML" totalLines="12" codeLines="12" commentLines="0" blankLines="0"/>
        <language name="Java" displayName="Java" totalLines="59" codeLines="21" commentLines="29" blankLines="9"/>
    </languages>
    <files numFiles="5" numUnrecognized="0" totalLines="78" codeLines="40" commentLines="29" blankLines="9">
        <file pathname="src/main/java/com/cthing/testproject/HelloWorld.java">
            <language name="Java" displayName="Java" totalLines="32" codeLines="11" commentLines="17" blankLines="4"/>
        </file>
        <file pathname="src/main/java/com/cthing/testproject/package-info.java">
            <language name="Java" displayName="Java" totalLines="10" codeLines="1" commentLines="8" blankLines="1"/>
        </file>
        <file pathname="src/main/resources/sample.css">
            <language name="Css" displayName="CSS" totalLines="7" codeLines="7" commentLines="0" blankLines="0"/>
        </file>
        <file pathname="src/main/resources/sample.html">
            <language name="Html" displayName="HTML" totalLines="12" codeLines="12" commentLines="0" blankLines="0"/>
        </file>
        <file pathname="src/test/java/com/cthing/testproject/HelloWorldTest.java">
            <language name="Java" displayName="Java" totalLines="17" codeLines="9" commentLines="4" blankLines="4"/>
        </file>
    </files>
</locc>
